export { default as Banner } from "./Banner";
export { default as Description } from "./Description";
export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as Map } from "./Map";
export { default as Menu } from "./Menu";
export { default as Message } from "./Message";
export { default as Parallax } from "./Parallax";
export { default as Partners } from "./Partners";
